import { existsSync, readFileSync } from "node:fs";

const files = {
  app: read("app.js"),
  server: read("server.js"),
  deploymentSecurity: read("server/deployment-security.js"),
  storage: read("server/storage.js"),
  styles: read("styles.css"),
  index: read("index.html"),
  serviceWorker: read("service-worker.js"),
  build: read("scripts/build.mjs"),
  auditSource: read("scripts/audit-source.mjs"),
  packageJson: JSON.parse(read("package.json")),
  envExample: read(".env.example"),
  readme: read("README.md"),
  checkPostgres: read("scripts/check-postgres-state.mjs"),
  checkDeploymentSecurity: read("scripts/check-deployment-security.mjs"),
  backupCli: read("scripts/manage-state-backups.mjs"),
  checkBackups: read("scripts/check-state-migration-backups.mjs"),
  railway: JSON.parse(read("railway.json")),
};

const checks = [
  ["Notion_like prototype directory is removed", () => !existsSync("Notion_like")],
  ["standalone HTML review artifact is removed", () => !existsSync("sygma-os-review.html")],
  ["nav buttons no longer use native draggable", () => !files.app.includes('draggable="true"')],
  ["obsolete Notion sync placeholder UI is removed", () => !files.app.includes("notion-final-sync") && !files.app.includes("Notion sync mode") && !files.app.includes("Notion 최종")],
  ["server delegates persistence to storage module", () => files.server.includes('import { createStorage } from "./server/storage.js"') && files.server.includes("storage = createStorage")],
  ["storage requires PostgreSQL", () => files.storage.includes("DATABASE_URL is required for PostgreSQL persistence.") && !files.storage.includes("writeTokenFile")],
  ["storage creates public and private PostgreSQL tables", () => files.storage.includes("CREATE TABLE IF NOT EXISTS app_state") && files.storage.includes("CREATE TABLE IF NOT EXISTS app_private_data")],
  ["storage atomically claims and consumes expiring OAuth transactions", () => files.storage.includes("CREATE TABLE IF NOT EXISTS app_oauth_transactions") && files.storage.includes("ON CONFLICT (app_state_id, kind, nonce) DO NOTHING") && files.storage.includes("WITH consumed AS") && files.server.includes('storage.claimOAuthTransaction(') && files.server.includes('storage.consumeOAuthTransaction(')],
  ["storage creates relational collection tables", () => files.storage.includes("CREATE TABLE IF NOT EXISTS tasks") && files.storage.includes("CREATE TABLE IF NOT EXISTS resources") && files.storage.includes("CREATE TABLE IF NOT EXISTS task_resources") && files.storage.includes("CREATE TABLE IF NOT EXISTS collection_links")],
  ["storage models task and resource relationships correctly", () => files.storage.includes("FOREIGN KEY (app_state_id, project_id) REFERENCES projects") && files.storage.includes("FOREIGN KEY (app_state_id, goal_id) REFERENCES goals") && files.storage.includes("FOREIGN KEY (app_state_id, box_id) REFERENCES boxes") && files.storage.includes("function taskResourceRelations(state, ids)") && files.storage.includes("task.resourceId")],
  ["storage reads app collections from relational tables", () => files.storage.includes("function readRelationalAppState(client, baseState, { normalize = true } = {})") && files.storage.includes("tasks: await readTasks(client, taskResources)") && files.storage.includes("resources: await readResources(client)") && files.storage.includes("links: await readCollectionLinks(client)")],
  ["storage syncs JSONB state into relational tables for writes, bootstrap, and migration healing", () => files.storage.includes("if (!authoritative.hasRelationalRows)") && files.storage.includes("if (authoritative.hasRelationalRows)") && files.storage.includes("await syncRelationalState(client, normalized.state)") && files.storage.includes("for (const table of RELATIONAL_DELETE_ORDER)")],
  ["storage snapshots authoritative state before automatic migration healing", () => files.storage.includes("CREATE TABLE IF NOT EXISTS app_state_migration_backups") && files.storage.includes("CREATE TABLE IF NOT EXISTS app_state_restore_history") && /const authoritative = await authoritativeStateSnapshot\(client, row\.state\);[\s\S]{0,900}?await insertMigrationBackup\(client, authoritative\.state, row\.revision, reason\);[\s\S]{0,500}?UPDATE app_state SET state/.test(files.storage)],
  ["migration backups have metadata-only listing and integrity digests", () => files.storage.includes("state_sha256 text NOT NULL") && files.storage.includes("function jsonSha256(value)") && files.storage.includes("return result.rows.map(migrationBackupMetadata)") && !/async function listMigrationBackups[\s\S]{0,1000}?SELECT[\s\S]{0,500}?backup\.state(?:\s|,)/.test(files.storage)],
  ["backup restore requires revision and creates a safety backup", () => files.storage.includes('throw storageError(428, "STATE_PRECONDITION_REQUIRED"') && files.storage.includes('throw storageError(409, "STATE_REVISION_CONFLICT"') && files.storage.includes("const safetyBackup = await insertMigrationBackup") && files.storage.includes("const restoredRevision = currentRevision + 1") && files.storage.includes("INSERT INTO app_state_restore_history")],
  ["backup CLI requires exact workspace confirmation and never prints state", () => files.backupCli.includes('confirmation !== appStateId') && files.backupCli.includes('"CONFIRMATION_REQUIRED"') && files.backupCli.includes('parsed.options.has("expected-revision")') && files.backupCli.includes("backup state is never printed") && !/\bstate\s*:/.test(files.backupCli)],
  ["isolated migration backup check covers v3 backup and restore", () => files.checkBackups.includes("legacyV3State") && files.checkBackups.includes("automatic_version_migration_v3_to_v4") && files.checkBackups.includes("CLI restore accepted a stale revision") && files.checkBackups.includes("backup/restore touched an unrelated sentinel workspace") && files.checkBackups.includes("DELETE FROM app_state_migration_backups WHERE app_state_id = ANY($1)")],
  ["state status exposes relational collection source", () => files.storage.includes('collectionSource: "relational"') && files.checkPostgres.includes('status.collectionSource === "relational"')],
  ["production and Railway state writes require revision preconditions", () => files.server.includes("deploymentSecurityPolicy(process.env)") && files.server.includes("const railwayRuntime = railwayRuntimeDetected(process.env)") && /const requireStatePrecondition = deploymentSecurity\.forceStatePrecondition[\s\S]{0,180}?\|\| railwayRuntime[\s\S]{0,180}?process\.env\.NODE_ENV === "production"/.test(files.server) && files.deploymentSecurity.includes('projectId: "623a83b1-085a-446a-8789-be57923a7058"') && files.deploymentSecurity.includes('environmentId: "0bd3f580-8f52-47e7-b69f-89f413176d3e"') && files.deploymentSecurity.includes('serviceId: "3a97e1c9-5424-4ec5-8da7-423b21f76785"') && files.railway.deploy?.startCommand === "npm run start:production"],
  ["production Google OAuth stays on the Railway origin with one-time state", () => files.deploymentSecurity.includes('googleRedirectUri: "https://personalweb-production-81a6.up.railway.app/api/google/oauth/callback"') && files.deploymentSecurity.includes('publicBaseUrl: "https://personalweb-production-81a6.up.railway.app"') && files.server.includes("function productionGoogleOAuthConfigurationValid()") && files.server.includes("function verifiedGoogleOAuthState(value)") && files.server.includes("function consumePendingGoogleOAuthState(state)") && !files.server.includes("GoogleOAuthHandoff") && !files.server.includes("GOOGLE_OAUTH_HANDOFF")],
  ["public Railway has no app access gate and still rejects cross-site browser mutations", () => !files.server.includes("createAccessController") && !files.server.includes("/auth/login") && !files.deploymentSecurity.includes("forceAppAccessAuth") && !files.envExample.includes("APP_ACCESS_PASSWORD_SHA256") && files.server.includes("mutationOriginAllowed(request, requestUrl, requireMutationOrigin)") && files.checkDeploymentSecurity.includes("native API mutation without browser metadata was rejected")],
  ["Google endpoints are rate limited and the shell is noindex", () => files.server.includes('operation === "google.status" || operation === "google.calendar.read"') && files.server.includes('operation === "google.connect.start"') && files.envExample.includes("API_RATE_LIMIT_GOOGLE_READ_MAX=120") && files.index.includes('<meta name="robots" content="noindex,nofollow">')],
  ["storage normalizes app state before JSONB writes", () => files.storage.includes("normalizeAppStateForStorage(state)") && files.storage.includes("delete nextState.settings.appMode") && files.storage.includes("for (const key of COLLECTION_KEYS)")],
  ["Task persistence is date-only and legacy time data migrates once", () => {
    const taskTable = sourceSection(files.storage, "CREATE TABLE IF NOT EXISTS tasks", "CREATE TABLE IF NOT EXISTS resources");
    const taskReader = sourceSection(files.storage, "async function readTasks", "async function readResources");
    const taskWriter = sourceSection(files.storage, "async function insertTasks", "async function insertResources");
    const taskFactory = sourceSection(files.app, "function createTask", "function createProject");
    const taskCalendar = sourceSection(files.app, "function getTaskCalendarEvents", "function getProjectCalendarEvents");
    const googleSync = sourceSection(files.app, "async function syncGoogleCalendar", "function googleSyncTaskCandidates");
    return files.app.includes("function normalizeTaskRecords(tasks)")
      && files.app.includes("function normalizeTaskDate(value)")
      && files.app.includes("nextState.tasks.some(taskNeedsDateOnlyMigration)")
      && files.storage.includes("function normalizeTaskForStorage(task)")
      && files.storage.includes("function normalizeTaskDate(value)")
      && files.storage.includes("if (!legacySomeday && !cleanTask.dueDate)")
      && !taskTable.includes("scheduled_start")
      && !taskTable.includes("estimated_minutes")
      && !taskReader.includes("scheduled_start")
      && !taskWriter.includes("scheduled_start")
      && !taskFactory.includes("scheduledStart")
      && !taskFactory.includes("estimatedMinutes")
      && taskCalendar.includes("allDay: true")
      && googleSync.includes("start: { date: task.dueDate }")
      && !googleSync.includes("dateTime:");
  }],
  ["legacy Task someday state migrates to scheduled without inventing dates and is not offered in the UI", () => {
    const taskStatuses = sourceSection(files.app, "task: {", "project: {");
    const taskDateChoices = sourceSection(files.app, "const TASK_DATE_CHOICE_DEFS", "const LEGACY_TASK_TIME_FIELDS");
    const clientMigration = sourceSection(files.app, "function normalizeTaskRecords", "function normalizeTaskDate");
    const storageMigration = sourceSection(files.storage, "function normalizeTaskForStorage", "function normalizeTaskDate");
    return !taskStatuses.includes("someday:")
      && !taskDateChoices.includes('[2, "예정"]')
      && clientMigration.includes('task.status === LEGACY_TASK_SOMEDAY_STATUS')
      && clientMigration.includes('cleanTask.status = legacySomeday ? "scheduled" : cleanTask.status')
      && clientMigration.includes('legacySomeday ? "" : legacyTaskDate(task.scheduledStart)')
      && storageMigration.includes('task.status === LEGACY_TASK_SOMEDAY_STATUS')
      && storageMigration.includes('cleanTask.status = legacySomeday ? "scheduled" : cleanTask.status')
      && storageMigration.includes('cleanTask.dueDate = normalizeTaskDate(cleanTask.dueDate)')
      && !files.app.includes('["waiting", "someday"]');
  }],
  ["storage enforces app state schema defaults", () => files.storage.includes("STATE_VERSION") && files.storage.includes("DEFAULT_NAV_ORDER") && files.storage.includes("DEFAULT_CALENDAR_SOURCES") && files.storage.includes("STRING_SETTING_KEYS") && files.storage.includes("statsDemoDataSeeded")],
  ["state writes strictly validate v4 payloads before storage mutation", () => files.server.includes("const STATE_VERSION = 4;") && files.server.includes("function validateIncomingState(state)") && /async function handleStateWrite\(request, response\) \{[\s\S]*?validateIncomingState\(body\.state\);[\s\S]*?storage\.writeAppState\(body\.state/.test(files.server) && files.server.includes('throw apiError(422, "INVALID_STATE"') && files.server.includes('"invalid_resource_locked"') && files.checkPostgres.includes("non-boolean Resource locked") && files.checkPostgres.includes("assertInvalidWriteDoesNotMutate(")],
  ["full-state API rejects permanent Resource omission inside the locked storage transaction", () => files.server.includes("rejectResourcePermanentDelete: true") && files.storage.includes("options.rejectResourcePermanentDelete === true") && files.storage.includes('"RESOURCE_PERMANENT_DELETE_DISABLED"') && files.storage.includes("const authoritative = await authoritativeStateSnapshot(client, currentRow?.state)") && files.checkPostgres.includes("assertResourcePermanentDeleteRejectedDoesNotMutate") && files.checkPostgres.includes("trusted operator storage reset could not intentionally replace Resource membership")],
  ["Resource API uses conditional incremental relational persistence", () => files.server.includes('return "resource.write"') && files.server.includes("async function handleResourceWrite(request, response, requestUrl)") && files.server.includes("storage.writeResource(body.resource") && files.server.includes("requirePrecondition: true") && files.storage.includes("async function writeResource(resource, options = {})") && files.storage.includes("SELECT state, revision FROM app_state WHERE id = $1 FOR UPDATE") && files.storage.includes("await upsertResource(client, resource, resourceIndex") && files.storage.includes("ON CONFLICT (app_state_id, id) DO UPDATE SET")],
  ["Resource API validates reconstructed state and preserves unrelated data", () => files.storage.includes("const currentState = await readRelationalAppState(client, normalized.state)") && files.storage.includes("options.validateState(nextState)") && files.checkPostgres.includes("async function checkIncrementalResourceApi()") && files.checkPostgres.includes("incremental Resource update clobbered an unrelated committed Resource") && files.checkPostgres.includes("cross-Resource duplicate block ID") && files.checkPostgres.includes("stale incremental Resource update did not return 409")],
  ["strictly rejected state writes do not silently filter or mutate collections", () => files.server.includes('"invalid_item"') && files.server.includes('"duplicate_id"') && files.server.includes('"broken_relation"') && files.server.includes('"unsupported_block_type"') && files.checkPostgres.includes("const before = await pool.query") && files.checkPostgres.includes("const after = await pool.query") && files.checkPostgres.includes("rejection changed the stored revision") && files.checkPostgres.includes("rejection mutated the stored state")],
  ["storage normalizes and heals app state reads", () => files.storage.includes("if (normalized.changed)") && files.storage.includes("UPDATE app_state SET state = $2::jsonb") && files.storage.includes("isValidDateString")],
  ["storage handles non-object PostgreSQL state rows", () => files.storage.includes("isPlainObject(state)") && files.storage.includes("let changed = !validRoot") && files.checkPostgres.includes("polluted-scalar-state")],
  ["client state normalization handles non-object payloads", () => files.app.includes('if (!next || typeof next !== "object" || Array.isArray(next)) next = {};')],
  ["client state normalization guards invalid collection arrays", () => files.app.includes("objectArrayWithoutLegacyKind(next.tasks, [])") && files.app.includes('objectArrayOrFallback(next.resources, fallbackCollection(fallbackState, "resources"))') && files.app.includes("objectArrayOrFallback(next.googleCalendars, [])")],
  ["client object array fallback avoids cloning valid arrays", () => files.app.includes("function objectArrayOrFallback(value, fallback)") && files.app.includes("let cleaned = null;") && files.app.includes("for (let index = 0; index < source.length; index += 1)") && files.app.includes("if (!cleaned) cleaned = source.slice(0, index);") && files.app.includes("return cleaned || source;") && !files.app.includes("return arrayOrFallback(value, fallback).filter(isPlainObject);")],
  ["client state normalization strips legacy kind in one pass", () => files.app.includes("function objectArrayWithoutLegacyKind(value, fallback)") && files.app.includes("const source = arrayOrFallback(value, fallback);") && files.app.includes("for (let index = 0; index < source.length; index += 1)") && files.app.includes("if (!cleaned) cleaned = source.slice(0, index);") && files.app.includes("const { kind, ...cleanItem } = item;") && files.app.includes("return cleaned || source;") && !files.app.includes(".map(({ kind, ...task }) => task)") && !files.app.includes(".map(({ kind, ...journal }) => journal)")],
  ["client state normalization guards settings object maps", () => files.app.includes("const nextSettings = isPlainObject(next.settings) ? next.settings : {}") && files.app.includes("settings.visibleGoogleCalendars = isPlainObject(settings.visibleGoogleCalendars)")],
  ["client calendar source normalization reuses valid settings", () => files.app.includes("const CALENDAR_SOURCE_KEYS = Object.keys(DEFAULT_CALENDAR_SOURCES)") && files.app.includes("function calendarSourcesValid(sources)") && files.app.includes("if (calendarSourcesValid(sources)) return sources;") && files.app.includes("for (const key of CALENDAR_SOURCE_KEYS)") && !files.app.includes("...(sources || {})")],
  ["client calendar source validation avoids key array allocation", () => files.app.includes("function calendarSourcesValid(sources)") && files.app.includes("let count = 0;") && files.app.includes("for (const key in sources)") && files.app.includes("return count === CALENDAR_SOURCE_KEYS.length;") && !files.app.includes("const keys = Object.keys(sources);")],
  ["client state normalization avoids eager demo data creation", () => /function normalizeState\(next\) \{[\s\S]*?let seeded = null;[\s\S]*?return ensureStatsDemoData\(normalized, \{ force: shouldSeedStatsDemo \}\);/.test(files.app)],
  ["client state normalization lazily creates minimal fallback state", () => files.app.includes("let seeded = null") && files.app.includes("const fallbackState = () => (seeded ||= createMinimalSeedState())") && files.app.includes("fallbackCollection(fallbackState")],
  ["client initial state avoids local workspace authority before PostgreSQL read", () => files.app.includes("return createMinimalSeedState();") && files.app.includes("initializeLocalResourcePersistence({ applySnapshot: false })") && !files.app.includes("const shouldUploadLocal = localStateChangedBeforeDatabaseReady")],
  ["workspace authority opens only after every initialization pass finishes", () => {
    const initializeNowBody = files.app.match(/async function initializeDatabaseStateNow\(\) \{([\s\S]*?)\n\}\n\nfunction rerenderAfterStateReplace/)?.[1] || "";
    return files.app.includes("initializationFinished && databaseBackendStatus.connected && !databaseBackendStatus.conflict")
      && !initializeNowBody.includes('setWorkspaceAuthorityMode("ready")');
  }],
  ["remote saves require verified workspace authority", () => files.app.includes('if (!databaseBackendStatus.connected || app.dataset.workspaceAuthority !== "ready") return;') && /async function flushRemoteStateSave[\s\S]*?app\.dataset\.workspaceAuthority !== "ready"/.test(files.app)],
  ["demo seed bulk generation avoids Array.from and flatMap", () => files.app.includes("const demoTasks = [];") && files.app.includes("for (let index = 0; index < 36; index += 1)") && files.app.includes("const dueDate = day(offset);") && files.app.includes("const demoResources = [];") && files.app.includes("for (let index = 0; index < 14; index += 1)") && files.app.includes("const demoHabitInstances = [];") && files.app.includes("for (let habitIndex = 0; habitIndex < demoHabits.length; habitIndex += 1)") && !files.app.includes("const demoTasks = Array.from") && !files.app.includes("const demoResources = Array.from") && !files.app.includes("const demoHabitInstances = demoHabits.flatMap") && !files.app.includes("new Date(day(offset)).toISOString()")],
  ["demo seed add-missing avoids map/forEach allocation", () => files.app.includes("function addMissingById(collection, items)") && files.app.includes("const existingIds = new Set();") && files.app.includes("for (const item of collection)") && files.app.includes("for (const item of items)") && !files.app.includes("new Set(collection.map((item) => item.id))") && !files.app.includes("items.forEach((item) => {\n    if (!existingIds.has(item.id))")],
  ["project calendar renders continuous range spans", () => files.app.includes("function projectCalendarSpanLayout(events, days)") && files.app.includes("function projectCalendarRowLayout(layout, days, rowStartIndex, rowLength, limit)") && files.app.includes("function renderProjectCalendarSpanLayer(rowLayout, limit)") && files.app.includes('class="calendar-span-layer project-calendar-span-layer"') && !files.app.includes("function renderProjectCalendarPill(")],
  ["project calendar preserves lanes across month rows", () => files.app.includes("const layout = projectCalendarSpanLayout(events, days);") && files.app.includes("const rowLayout = projectCalendarRowLayout(layout, days, index, weekDays.length, 4);") && files.app.includes("if (segment.lane >= limit)") && files.app.includes("grid-row: ${segment.lane + 1}") && !files.app.includes("calendarSpanSegments(events, weekDays")],
  ["Goal cards expose inline edit and confirmed delete controls", () => files.app.includes('data-goal-edit="${goal.id}"') && files.app.includes('data-goal-delete="${goal.id}"') && files.app.includes("function openGoalEditor(goalId)") && files.app.includes("function renderGoalDeleteConfirm()") && files.app.includes('deleteEntity("goals", targetId)')],
  ["Box cards expose inline edit and confirmed delete controls", () => files.app.includes('data-box-edit="${box.id}"') && files.app.includes('data-box-delete="${box.id}"') && files.app.includes("function openBoxEditor(boxId)") && files.app.includes("function renderBoxDeleteConfirm()") && files.app.includes('deleteEntity("boxes", targetId)')],
  ["entity deletion removes polymorphic relation links and queues a workspace save", () => files.app.includes("function removeDeletedEntityLinks(type, itemId)") && files.app.includes("const fromMatches = link?.fromId === itemId") && files.app.includes("const toMatches = link?.toId === itemId") && files.app.includes("state.links.length = writeIndex") && /function deleteEntity[\s\S]*?localWorkspaceOperationRequired = true;[\s\S]*?localWorkspaceOperationScope = "workspace";/.test(files.app)],
  ["calendar controls count Google events with one direct pass", () => files.app.includes("function eventCountsByCalendarId(events)") && files.app.includes("const googleEventCounts = eventCountsByCalendarId(googleEvents)") && files.app.includes("for (const event of events)") && !files.app.includes("events.forEach((event) => {\n    const calendarId = event.calendarId || \"primary\";") && !files.app.includes("googleEvents.filter((event) => event.calendarId === calendar.id).length")],
  ["calendar event builders avoid filter-map chains", () => files.app.includes("function getGoogleCalendarEvents({ visibleOnly = false } = {})") && files.app.includes("const visibleGoogleEvents = getVisibleGoogleCalendarEvents()") && files.app.includes("if (visibleOnly && !googleCalendarVisible(event.calendarId || \"primary\")) continue;") && !files.app.includes(".filter((task) => task.dueDate") && !files.app.includes(".filter((project) => (project.startDate || project.endDate)") && !files.app.includes("googleEvents.filter((event) => googleCalendarVisible(event.calendarId || \"primary\"))")],
  ["calendar event builders use direct loops", () => files.app.includes("function getTaskCalendarEvents()") && files.app.includes("for (const task of state.tasks)") && files.app.includes("function getProjectCalendarEvents()") && files.app.includes("for (const project of state.projects)") && files.app.includes("for (const event of state.googleEvents || [])") && !/function getTaskCalendarEvents\(\) \{[\s\S]*?state\.tasks\.forEach[\s\S]*?function getProjectCalendarEvents/.test(files.app) && !/function getProjectCalendarEvents\(\) \{[\s\S]*?state\.projects\.forEach[\s\S]*?function getGoogleCalendarEvents/.test(files.app) && !/function getGoogleCalendarEvents\(\{ visibleOnly = false \} = \{\}\) \{[\s\S]*?\(state\.googleEvents \|\| \[\]\)\.forEach[\s\S]*?function getVisibleGoogleCalendarEvents/.test(files.app)],
  ["Google calendar normalization avoids map-filter chains", () => files.app.includes("function normalizeGoogleCalendarEntries(entries = [])") && files.app.includes("function normalizeGoogleApiEvents(entries = [])") && files.app.includes("const calendars = normalizeGoogleCalendarEntries(payload.calendars)") && files.app.includes("state.googleEvents = normalizeGoogleApiEvents(payload.events)") && files.app.includes("const googleCalendars = normalizeGoogleCalendarEntries(objectArrayOrFallback(next.googleCalendars, []))") && !files.app.includes(".map(normalizeGoogleCalendarEntry).filter(Boolean)") && !files.app.includes(".map((entry) => normalizeGoogleApiEvent(entry.event, entry.calendar))")],
  ["Google calendar normalization uses direct loops", () => files.app.includes("function normalizeGoogleCalendarEntries(entries = [])") && files.app.includes("for (const entry of entries)") && files.app.includes("function ensureGoogleCalendarVisibility(calendars)") && files.app.includes("for (const calendar of calendars)") && files.app.includes("function normalizeGoogleApiEvents(entries = [])") && !files.app.includes("entries.forEach((entry)") && !files.app.includes("calendars.forEach((calendar)")],
  ["Google calendar options merge with direct loops", () => files.app.includes("function getGoogleCalendarOptions()") && files.app.includes("for (const calendar of state.googleCalendars || [])") && files.app.includes("for (const event of state.googleEvents || [])") && files.app.includes("for (const calendar of calendarsById.values())") && !files.app.includes("(state.googleCalendars || []).forEach((calendar)") && !files.app.includes("return Array.from(calendarsById.values()).sort")],
  ["calendar themes persist stable ID assignments and resolve exhausted palettes", () => files.app.includes("const GOOGLE_CALENDAR_COLOR_PALETTE = Object.freeze([") && files.app.includes("function stableCalendarColorIndex(value)") && files.app.includes("const identity = `google:${calendarId}`") && files.app.includes("function derivedGoogleCalendarColor(identity, attempt)") && files.app.includes("if (!usedColors.has(color)) return color;") && files.app.includes("assignments[calendarId] = color;") && files.app.includes("state.settings.calendarColorAssignments = allocation.assignments") && files.app.includes("googleCalendarThemeAssignments(calendars);")],
  ["calendar theme colors are canonicalized and use safe contrast fallbacks", () => files.app.includes("function sanitizeCalendarHexColor(value, fallback = \"\")") && files.app.includes("/^#[0-9a-f]{6}$/i.test(color)") && files.app.includes("/^#[0-9a-f]{3}$/i.test(color)") && files.app.includes('calendarContrastColor(color, color === preferred ? calendar.foregroundColor : "")') && files.app.includes("sanitizeCalendarHexColor(theme.contrast, calendarContrastColor(color))") && !files.app.includes("/^#[0-9a-f]{3,8}$/i")],
  ["calendar render pipeline propagates sanitized theme assignments", () => {
    const renderer = sourceSection(files.app, "function renderCalendar()", "function combinedCalendarSourceEvents");
    const declarations = sourceSection(files.app, "function calendarColorDeclarations", "function renderDetail");
    return renderer.includes("const calendarThemes = googleCalendarThemeAssignments()")
      && renderer.includes("renderCalendarControls(taskEvents, projectEvents, googleEvents, calendarThemes)")
      && renderer.includes("renderWeekDays(combinedEvents, calendarThemes)")
      && renderer.includes("renderCalendarLegend(combinedEvents, calendarThemes)")
      && renderer.includes("renderCalendarAgenda(combinedEvents, calendarThemes)")
      && renderer.includes("renderCombinedCalendar(combinedEvents, calendarThemes)")
      && declarations.includes("const theme = calendarThemeFor(calendar, calendarThemes)")
      && declarations.includes("sanitizeCalendarHexColor(theme.color")
      && declarations.includes("sanitizeCalendarHexColor(theme.contrast")
      && declarations.includes('return `--calendar-color: ${color}; --calendar-contrast: ${contrast};`;');
  }],
  ["calendar theme assignments cross every renderer edge", () => {
    const controls = sourceSection(files.app, "function renderCalendarControls", "function renderGoogleCalendarToggles");
    const googleToggles = sourceSection(files.app, "function renderGoogleCalendarToggles", "function renderCalendarLegend");
    const legend = sourceSection(files.app, "function renderCalendarLegend(events, calendarThemes)", "function renderCalendarLegendItem");
    const week = sourceSection(files.app, "function renderWeekDays", "function renderCombinedCalendar");
    const month = sourceSection(files.app, "function renderCombinedCalendar", "function renderCalendarAgenda");
    const agenda = sourceSection(files.app, "function renderCalendarAgenda", "function calendarAgendaItems");
    const monthDays = sourceSection(files.app, "function renderCombinedCalendarDays", "function chunkCalendarWeeks");
    const spanLayer = sourceSection(files.app, "function renderCalendarSpanLayer", "function calendarSpanSegments");
    const spanEvents = sourceSection(files.app, "function renderCalendarEvents", "function calendarSpanSort");
    return controls.includes("renderGoogleCalendarToggles(googleCalendars, googleEventCounts, calendarThemes)")
      && googleToggles.includes("renderGoogleCalendarToggle(calendar, eventCounts, calendarThemes)")
      && legend.includes("renderCalendarLegendItem") && legend.includes("calendarThemes")
      && (legend.match(/renderCalendarLegendItem\([\s\S]*?calendarThemes\);/g) || []).length === 3
      && week.includes("calendarThemes })")
      && month.includes("renderCombinedCalendarDays(weekDays, events, currentMonth, today, calendarThemes)")
      && agenda.includes("renderCalendarAgendaItem(item, calendarThemes)")
      && monthDays.includes("calendarThemes })")
      && spanLayer.includes("renderCalendarEvents(segments, { compact: true, limit: segments.length, calendarThemes })")
      && spanEvents.includes("renderCalendarSpanEvent(events[index], { compact, calendarThemes })");
  }],
  ["calendar event views share one color declaration contract", () => {
    const spanStart = files.app.indexOf("function renderCalendarSpanEvent");
    const spanEnd = files.app.indexOf("function calendarSpanTimeLabel", spanStart);
    const agendaStart = files.app.indexOf("function renderCalendarAgendaItem");
    const agendaEnd = files.app.indexOf("function calendarAgendaDateLabel", agendaStart);
    const spanRenderer = spanStart >= 0 && spanEnd > spanStart ? files.app.slice(spanStart, spanEnd) : "";
    const agendaRenderer = agendaStart >= 0 && agendaEnd > agendaStart ? files.app.slice(agendaStart, agendaEnd) : "";
    return spanRenderer.includes("calendarColorDeclarations(event, calendarThemes)")
      && agendaRenderer.includes("calendarColorDeclarations(event, calendarThemes)")
      && spanRenderer.includes('target="_blank" rel="noreferrer"')
      && agendaRenderer.includes('target="_blank" rel="noreferrer"')
      && !spanRenderer.includes('tabindex="0"');
  }],
  ["calendar legend and each toggle renderer expose per-calendar themes", () => {
    const legend = sourceSection(files.app, "function renderCalendarLegendItem", "function renderCalendarMonthPanelHeader");
    const localToggle = sourceSection(files.app, "function renderCalendarSourceToggle", "function renderGoogleCalendarToggle");
    const googleToggle = sourceSection(files.app, "function renderGoogleCalendarToggle", "function eventCountsByCalendarId");
    return legend.includes('class="calendar-legend-chip" style="${calendarColorDeclarations(calendar, calendarThemes)}"')
      && localToggle.includes('class="calendar-toggle" style="${calendarColorDeclarations(calendar, calendarThemes)}"')
      && googleToggle.includes('class="calendar-toggle calendar-google-toggle" style="${calendarColorDeclarations({ ...calendar, source: "google", calendarId: calendar.id }, calendarThemes)}"');
  }],
  ["calendar CSS consumes shared accent variables across all event surfaces", () => {
    const toggle = sourceSection(files.styles, ".calendar-toggle {", ".calendar-toggle:hover");
    const legend = sourceSection(files.styles, ".calendar-legend-chip {", ".calendar-legend-chip span");
    const dot = sourceSection(files.styles, ".source-dot {", ".day {");
    const span = sourceSection(files.styles, ".calendar-span-event {", ".calendar-span-event:hover");
    const agenda = sourceSection(files.styles, ".calendar-agenda-row {", ".calendar-agenda-row:hover");
    const agendaTime = sourceSection(files.styles, ".calendar-agenda-row time {", ".calendar-agenda-open {");
    return toggle.includes("border: 1px solid color-mix(in srgb, var(--calendar-color)")
      && toggle.includes("linear-gradient(135deg, color-mix(in srgb, var(--calendar-color)")
      && legend.includes("border: 1px solid color-mix(in srgb, var(--calendar-color)")
      && legend.includes("background: color-mix(in srgb, var(--calendar-color)")
      && dot.includes("background: var(--calendar-color, var(--blue));")
      && span.includes("--span-bg:") && span.includes("var(--calendar-color)")
      && span.includes("--span-border: color-mix(in srgb, var(--calendar-color)")
      && span.includes("border: 1px solid var(--span-border);")
      && span.includes("background: var(--span-bg);")
      && agenda.includes("border: 1px solid color-mix(in srgb, var(--calendar-color)")
      && agenda.includes("box-shadow: inset 3px 0 0 var(--calendar-color)")
      && agendaTime.includes("background: color-mix(in srgb, var(--calendar-color)")
      && agendaTime.includes("color: color-mix(in srgb, var(--calendar-color)");
  }],
  ["Google sync candidates avoid direct state task filter", () => files.app.includes("function googleSyncTaskCandidates()") && files.app.includes("const tasks = googleSyncTaskCandidates()") && files.app.includes("if (task.dueDate && task.status !== \"done\" && !task.googleEventId) tasks.push(task);") && !files.app.includes("state.tasks.filter((task) => task.dueDate && task.status !== \"done\" && !task.googleEventId)")],
  ["Google sync candidates use a direct loop", () => files.app.includes("function googleSyncTaskCandidates()") && files.app.includes("for (const task of state.tasks)") && !/function googleSyncTaskCandidates\(\) \{[\s\S]*?state\.tasks\.forEach[\s\S]*?function upsertGoogleEvents/.test(files.app)],
  ["Google sync upserts events once after task loop", () => files.app.includes("const syncedEvents = [];") && files.app.includes("upsertGoogleEvents(syncedEvents)") && files.app.includes("function upsertGoogleEvents(events = [])") && files.app.includes("const incomingById = new Map();") && !files.app.includes("state.googleEvents = [...(state.googleEvents || []).filter((entry) => entry.id !== normalized.id), normalized]")],
  ["Google sync upsert avoids forEach and spread merging", () => files.app.includes("function upsertGoogleEvents(events = [])") && files.app.includes("for (const event of events)") && files.app.includes("for (const event of state.googleEvents || [])") && files.app.includes("for (const event of incomingById.values())") && files.app.includes("state.googleEvents = nextEvents;") && !/function upsertGoogleEvents\(events = \[\]\) \{[\s\S]*?\.forEach[\s\S]*?function exportJson/.test(files.app) && !files.app.includes("state.googleEvents = [...nextEvents, ...incomingById.values()]")],
  ["task board classifies tasks in one pass without page search", () => files.app.includes("function taskBoardBuckets(tasks, today, tomorrow)") && files.app.includes("const filteredTasks = controlledItems(\"tasks\", state.tasks, \"tasks\"") && files.app.includes("const { todayTasks, tomorrowTasks, scheduled, overdue, unplannedOnly, completed } = taskBoardBuckets(filteredTasks, today, tomorrow)") && !files.app.includes("if (!matchesSearch(task.title, searchQuery)) continue;") && !files.app.includes("state.tasks.filter((task) => matchesSearch") && !files.app.includes("const active = filtered.filter((task)") && !files.app.includes("const overdueIds = new Set(overdue.map((task) => task.id))")],
  ["task board buckets use a direct loop", () => files.app.includes("function taskBoardBuckets(tasks, today, tomorrow)") && files.app.includes("for (const task of tasks)") && !/function taskBoardBuckets\(tasks, today, tomorrow\) \{[\s\S]*?tasks\.forEach[\s\S]*?function isTaskOnDate/.test(files.app)],
  ["today dashboard classifies tasks in one pass", () => files.app.includes("function todayTaskBuckets(today, tomorrow, tasks = state.tasks)") && files.app.includes("const controlledTasks = controlledItems(\"tasks\", state.tasks, \"today\"") && files.app.includes("todayTaskBuckets(today, tomorrow, controlledTasks)") && !files.app.includes("const activeTodayTasks = state.tasks.filter((task) => isTaskOnDate(task, today)")],
  ["today dashboard task buckets use a direct loop", () => files.app.includes("function todayTaskBuckets(today, tomorrow, tasks = state.tasks)") && files.app.includes("for (const task of tasks)") && !/function todayTaskBuckets\(today, tomorrow, tasks = state\.tasks\) \{[\s\S]*?tasks\.forEach[\s\S]*?function sortTaskBoardBuckets/.test(files.app)],
  ["today dashboard secondary data avoids direct state filters", () => files.app.includes("function todayDashboardCollections(resources = state.resources, habits = state.habits, projects = state.projects)") && files.app.includes("controlledItems(\"resources\", state.resources, \"today\")") && files.app.includes("collections.activeProjectCount += 1") && !files.app.includes("state.projects.filter((project) => [\"active\", \"focus\"].includes(project.status))") && !files.app.includes("state.resources.filter((resource) => resource.pinned && resource.importance !== \"archived\")") && !files.app.includes("state.habits.filter((habit) => habit.status === \"active\")")],
  ["today dashboard secondary buckets use direct loops", () => files.app.includes("function todayDashboardCollections(resources = state.resources, habits = state.habits, projects = state.projects)") && files.app.includes("for (const project of projects)") && files.app.includes("for (const resource of resources)") && files.app.includes("for (const habit of habits)") && !files.app.includes("state.projects.forEach((project) => {\n    if (project.status === \"active\" || project.status === \"focus\")") && !files.app.includes("state.resources.forEach((resource) => {\n    if (resource.pinned && resource.importance !== \"archived\")") && !files.app.includes("state.habits.forEach((habit) => {\n    if (habit.status === \"active\")")],
  ["scheduler lane targets count tasks in one pass", () => files.app.includes("function schedulerLaneCounts(excludedTaskId, today, tomorrow)") && files.app.includes("const schedulerCounts = schedulerLaneCounts(excludedTaskId, today, tomorrow)") && files.app.includes("isOverdueOnDate(task, today)") && !files.app.includes("active.filter((task) => isTaskOnDate(task, today)).length")],
  ["scheduler lane counts use a direct loop", () => files.app.includes("function schedulerLaneCounts(excludedTaskId, today, tomorrow)") && files.app.includes("for (const task of state.tasks)") && !/function schedulerLaneCounts\(excludedTaskId, today, tomorrow\) \{[\s\S]*?state\.tasks\.forEach[\s\S]*?function schedulerTaskCountsByDate/.test(files.app)],
  ["scheduler month grid reuses date counts", () => files.app.includes("function schedulerTaskCountsByDate(excludedTaskId)") && files.app.includes("const dayTaskCounts = schedulerTaskCountsByDate(task.id)") && files.app.includes("const count = dayTaskCounts.get(key) || 0") && !files.app.includes("state.tasks.filter((entry) => isTaskOnDate(entry, key)")],
  ["scheduler month task counts use a direct loop", () => files.app.includes("function schedulerTaskCountsByDate(excludedTaskId)") && files.app.includes("for (const task of state.tasks)") && !/function schedulerTaskCountsByDate\(excludedTaskId\) \{[\s\S]*?state\.tasks\.forEach[\s\S]*?function shortDateLabel/.test(files.app)],
  ["date labels parse date strings without split-map allocations", () => files.app.includes("const year = Number(text.slice(0, 4));") && files.app.includes("const month = Number(text.slice(5, 7));") && files.app.includes("const day = Number(text.slice(8, 10));") && !files.app.includes('split("-").map(Number)')],
  ["scheduler month task date counts avoid filter set allocation", () => files.app.includes("const dueDate = task.dueDate;") && files.app.includes("if (dueDate) counts.set(dueDate, (counts.get(dueDate) || 0) + 1);") && !files.app.includes("taskScheduledDate")],
  ["date range generation avoids Array.from callbacks", () => files.app.includes("function dateRange(start, count)") && files.app.includes("function dateKeyRange(start, count)") && files.app.includes("function renderWeekdayLabels(start, includeWeekendClass = false)") && files.app.includes("const days = dateRange(start, 7)") && files.app.includes("return dateKeyRange(start, count);") && files.app.includes("return dateRange(start, 42);") && !files.app.includes("Array.from({ length: 7 }, (_, index) => addDays") && !files.app.includes("Array.from({ length: 7 }, (_, index) => `<span>${weekday(addDays") && !files.app.includes("Array.from({ length: count }, (_, index) => dateKey(addDays") && !files.app.includes("Array.from({ length: 42 }, (_, index) => addDays") && !files.app.includes("Array.from({ length: totalDays }, (_, index) => addDays")],
  ["date and time formatters are shared instead of recreated per call", () => files.app.includes("const KOREAN_MONTH_FORMATTER = new Intl.DateTimeFormat") && files.app.includes("const KOREAN_DATE_TIME_FORMATTER = new Intl.DateTimeFormat") && files.app.includes("return KOREAN_MONTH_FORMATTER.format(date);") && files.app.includes("return KOREAN_DATE_TIME_FORMATTER.format(new Date(value));") && (files.app.match(/new Intl\.DateTimeFormat/g) || []).length === 6],
  ["block type metadata is cached for filtered slash menu navigation", () => files.app.includes("const BLOCK_TYPE_ENTRIES = Object.entries(BLOCK_TYPES);") && files.app.includes("const SLASH_ACTION_ENTRIES = [") && files.app.includes("const BLOCK_TYPE_SEARCH_ALIASES = {") && files.app.includes("const SLASH_ACTION_SEARCH_ALIASES = {") && files.app.includes('heading1: ["h1", "heading1", "heading 1", "title", "제목1", "#"]') && files.app.includes("function renderSlashMenuItems(ownerType, ownerId, blockId, selectedIndex, entries = BLOCK_TYPE_ENTRIES)") && files.app.includes('data-slash-action="${type}"') && files.app.includes("function slashMenuEntries(query = \"\", mode = \"block\")") && files.app.includes("const entries = includeActions ? [...BLOCK_TYPE_ENTRIES, ...SLASH_ACTION_ENTRIES] : BLOCK_TYPE_ENTRIES;") && files.app.includes("function slashHashBlockType(normalizedQuery = \"\")") && files.app.includes("applySlashBlockAction(slash.ownerType, slash.ownerId, slash.blockId, selectedType, slash.range)") && !files.app.includes("const entries = Object.entries(BLOCK_TYPES)") && !files.app.includes("const count = Object.keys(BLOCK_TYPES).length") && !files.app.includes("const types = Object.keys(BLOCK_TYPES)") && !files.app.includes("BLOCK_TYPE_ENTRIES\n        .map")],
  ["static menus and scheduler grid render with direct loops", () => files.app.includes("const COMMAND_MENU_ITEMS = [") && files.app.includes('const SCHEDULER_WEEKDAY_LABELS = ["월", "화", "수", "목", "금", "토", "일"];') && files.app.includes("function renderCommandMenuItems()") && files.app.includes("function renderSchedulerLanes(lanes, dragOverTarget)") && files.app.includes("function renderSchedulerWeekdayLabels()") && files.app.includes("function renderSchedulerMonthDays(days, monthDate, today, scheduledDate, dayTaskCounts, dragOverTarget)") && files.app.includes("for (const [action, icon, title, desc] of COMMAND_MENU_ITEMS)") && files.app.includes("for (const day of SCHEDULER_WEEKDAY_LABELS)") && files.app.includes("for (const lane of lanes)") && files.app.includes("for (const day of days)") && !files.app.includes("function renderCommandMenu() {\n  const commands = [") && !files.app.includes('${["월", "화", "수", "목", "금", "토", "일"].map') && !files.app.includes("COMMAND_MENU_ITEMS\n        .map") && !files.app.includes("SCHEDULER_WEEKDAY_LABELS.map") && !files.app.includes("laneTargets.map") && !files.app.includes("days.map((day) => {\n            const key = dateKey(day);")],
  ["entity stats use indexed relation maps instead of repeated scans", () => files.app.includes("function goalStatsRelations(goal)") && files.app.includes("function boxStatsRelations(box)") && files.app.includes("index.tasksByProjectId.get(project.id)") && files.app.includes("index.tasksByGoalId.get(goal.id)") && !files.app.includes("projects.some((project) => project.id === task.projectId)") && !files.app.includes("goals.some((goal) => goal.id === task.goalId)")],
  ["nav order normalization reuses cached key maps", () => files.app.includes("const DEFAULT_NAV_ORDER = NAV_ITEMS.map") && files.app.includes("const NAV_ITEMS_BY_KEY = new Map") && files.app.includes("const NAV_KEY_SET = new Set(DEFAULT_NAV_ORDER)") && files.app.includes("normalizedKeys.has(key)") && files.app.includes("for (const key of order)") && files.app.includes("for (const key of DEFAULT_NAV_ORDER)")],
  ["nav buttons render with a direct indexed loop", () => files.app.includes("function renderNavButtons()") && files.app.includes("const items = orderedNavItems();") && files.app.includes("for (let index = 0; index < items.length; index += 1)") && files.app.includes("const [key, label, icon] = items[index];") && !/function renderNavButtons\(\) \{[\s\S]*?orderedNavItems\(\)\s*\.map/.test(files.app)],
  ["ordered nav items avoid map-filter chains", () => files.app.includes("function orderedNavItems()") && files.app.includes("const items = [];") && files.app.includes("for (const key of normalizeNavOrder(state?.settings?.navOrder))") && files.app.includes("if (item) items.push(item);") && !files.app.includes("normalizeNavOrder(state?.settings?.navOrder).map((key) => NAV_ITEMS_BY_KEY.get(key)).filter(Boolean)")],
  ["block text extraction avoids map-filter chains", () => files.app.includes("function blockText(item)") && files.app.includes('text = text ? `${text} ${block.text}` : block.text;') && !files.app.includes("(item.blocks || []).map((block) => block.text).filter(Boolean).join(\" \")")],
  ["block text extraction uses a direct loop", () => files.app.includes("function blockText(item)") && files.app.includes("for (const block of item.blocks || [])") && !/function blockText\(item\) \{[\s\S]*?\(item\.blocks \|\| \[\]\)\.forEach/.test(files.app)],
  ["only resources keep persisted scoped search controls", () => files.app.includes("function viewControl(view = ui.view)") && files.app.includes("function controlledItems(type, items, view, context = {})") && files.app.includes('const query = type === "resources" ? (control.search || "").trim().toLowerCase() : "";') && files.app.includes('if (field === "search" && view !== "resources") return;') && !files.app.includes("ui.search") && !files.app.includes("data-action-input='search'") && files.storage.includes('resources: { search: "", searchScope: "fullText", filters: ["active"]') && files.storage.includes("controls[key].searchScope = normalizeResourceSearchScope(saved.searchScope)") && !files.storage.includes('today: { search: ""')],
  ["every main view renders unified filter and sort controls", () => files.app.includes("function renderViewControls(view, meta = {})") && files.app.includes('renderViewControls("today"') && files.app.includes('renderViewControls("inbox"') && files.app.includes('renderViewControls("tasks"') && files.app.includes('renderViewControls("projects"') && files.app.includes('renderViewControls("goals"') && files.app.includes('renderViewControls("boxes"') && files.app.includes('renderViewControls("resources"') && files.app.includes('renderViewControls("habits"') && files.app.includes('renderViewControls("journal"') && files.app.includes('renderViewControls("calendar"') && files.app.includes('renderViewControls("database"')],
  ["v4 Resource view settings persist through PostgreSQL", () => files.app.includes("const APP_STATE_VERSION = 4;") && files.app.includes("settings.viewControls = normalizeViewControls(settings.viewControls)") && files.app.includes("settings.openPagesIn = normalizeResourceOpenPagesIn(nextSettings.openPagesIn)") && files.app.includes("controls[key].searchScope = normalizeResourceSearchScope(saved.searchScope)") && files.app.includes("openPagesIn: { ...DEFAULT_RESOURCE_OPEN_PAGES_IN }") && files.storage.includes("const STATE_VERSION = 4;") && files.storage.includes('searchScope: "fullText"') && files.storage.includes("function normalizeResourceSearchScope(value)") && files.storage.includes("function normalizeResourceOpenPagesIn(value)") && files.storage.includes("nextState.settings.openPagesIn") && files.checkPostgres.includes("Resource searchScope changed during PostgreSQL round trip") && files.checkPostgres.includes("Resource openPagesIn changed during PostgreSQL round trip")],
  ["resource page uses unified filters without legacy filter buttons", () => files.app.includes("function renderResourceVault(resources, buckets, control)") && files.app.includes("function renderResourceLibrary(buckets)") && files.app.includes("function renderResourceList(resources)") && files.app.includes("function renderResourceMap(resources)") && files.styles.includes(".resource-vault") && files.styles.includes(".resource-map-node") && !files.app.includes("function renderResourceToggleFilters") && !files.app.includes("function renderResourceTypeFilters") && !files.app.includes("data-resource-type-filter") && !files.app.includes("data-view-control-toggle") && !files.styles.includes(".view-toggle-pill") && !files.styles.includes(".resource-type-chip") && !files.styles.includes(".resource-type-row")],
  ["relationship id lookups reuse collection id maps", () => files.app.includes("const collectionIndexCache = new Map()") && files.app.includes("function collectionIdMap(type)") && files.app.includes("for (const entry of collection)") && files.app.includes("function itemById(type, itemId)") && files.app.includes("const item = itemById(type, itemId)") && files.app.includes('const capture = itemById("captures", captureId)') && !files.app.includes("collection.forEach((entry) =>") && !/getCollection\([^\n]+?\)\.find\(\(entry\) => entry\.id/.test(files.app) && !/state\.(?:captures|goals|projects|resources|tasks|habits)\.find\(\(entry\) => entry\.id/.test(files.app)],
  ["state id indexes clear around route-aware replacement and mutation", () => /function rerenderAfterStateReplace\(\) \{\s*clearResourceTransientState\(\);\s*clearStateIndexes\(\);[\s\S]{0,420}?applyResourceRoute\(/.test(files.app) && /function saveState\([^)]*\) \{[\s\S]{0,260}?clearStateIndexes\(\);\s*state\.version/.test(files.app) && /state = normalizeState\(payload\.state\);\s*state\.revision = savedRevision;\s*clearStateIndexes\(\);/.test(files.app)],
  ["entity delete cleanup avoids spread/filter allocations", () => files.app.includes("function clearFieldValue(collection, field, value)") && files.app.includes("function removeByFieldInPlace(collection, field, value)") && files.app.includes('clearFieldValue(state.tasks, "resourceId", itemId);') && files.app.includes('removeByFieldInPlace(state.habitInstances, "habitId", itemId);') && files.app.includes("for (const capture of state.captures)") && !files.app.includes("[...state.goals, ...state.projects") && !files.app.includes("[...state.tasks, ...state.resources") && !files.app.includes("ui.resourceNotes = ui.resourceNotes.filter") && !files.app.includes("state.habitInstances = state.habitInstances.filter")],
  ["habit completion lookups reuse habit instance indexes", () => files.app.includes("let habitInstanceIndexCache = null") && files.app.includes("function habitInstanceIndex()") && files.app.includes("completedByHabitMonth") && files.app.includes("return habitInstanceIndex().completedByHabitDate.has") && files.app.includes("let instance = habitInstanceForDate(habitId, date)") && files.app.includes("for (const instance of collection)") && !files.app.includes("collection.forEach((instance) =>") && !files.app.includes("state.habitInstances.find((entry) => entry.habitId === habitId && entry.date === date") && !files.app.includes("state.habitInstances.filter((entry) => entry.habitId === habitId")],
  ["habit progress counts avoid filter-length allocation", () => files.app.includes("function habitDoneCount(habitId, dates)") && files.app.includes("let completed = 0;") && files.app.includes("for (const date of dates)") && files.app.includes("const completed = habitDoneCount(habit.id, days);") && !files.app.includes("dates.forEach((date) =>") && !files.app.includes("days.filter((date) => habitDone(habit.id, date)).length")],
  ["habit inline DOM progress counts avoid Array.from filter", () => files.app.includes('const rangeDays = card.querySelectorAll(".habit-day");') && files.app.includes("rangeDays.forEach((entry) =>") && files.app.includes('if (entry.classList.contains("is-done")) doneCount += 1;') && !files.app.includes('Array.from(card.querySelectorAll(".habit-day"))') && !files.app.includes('rangeDays.filter((entry) => entry.classList.contains("is-done")).length')],
  ["habit render reuses one today key per render", () => files.app.includes("function habitStatusBuckets(habits = state.habits)") && files.app.includes("const habits = controlledItems(\"habits\", state.habits, \"habits\", { today })") && files.app.includes("renderHabitItem(habit, today)") && files.app.includes("function renderHabitDayButton(habit, date, today = dateKey(new Date()))") && files.app.includes('date === today ? "is-today"') && !files.app.includes("`${state.habits.filter((habit) => habit.status === \"active\").length}개 활성`") && !files.app.includes("date === dateKey(new Date()) ? \"is-today\"")],
  ["habit render buckets use direct loops", () => files.app.includes("function habitStatusBuckets(habits = state.habits)") && files.app.includes("for (const habit of habits)") && !files.app.includes("habits.forEach((habit)")],
  ["project box resource boards classify collections once", () => files.app.includes("function projectStatusBuckets(projects = state.projects)") && files.app.includes("const projectBuckets = projectStatusBuckets(projects)") && files.app.includes("function boxVisibilityBuckets(boxes = state.boxes, excludedId = \"\")") && files.app.includes("const boxBuckets = boxVisibilityBuckets(boxes)") && files.app.includes("function resourceDisplayBuckets(resources = state.resources, excludedId = \"\")") && files.app.includes("const resourceBuckets = resourceDisplayBuckets(resources)") && !files.app.includes("const active = state.projects.filter((project)") && !files.app.includes("state.boxes.filter((box) => box.visibility") && !files.app.includes("renderResourceColumn(\"고정\", resources.filter")],
  ["project box resource boards classify with direct loops", () => files.app.includes("for (const project of projects)") && files.app.includes('project.status === "active" || project.status === "focus"') && files.app.includes("for (const box of boxes)") && files.app.includes("if (box.id === excludedId) continue;") && files.app.includes("for (const resource of resources)") && files.app.includes("if (resource.id === excludedId) continue;") && !files.app.includes("projects.forEach((project) => {\n    if ([\"active\", \"focus\"].includes(project.status))") && !files.app.includes("boxes.forEach((box) => {\n    if (box.id === excludedId) return;") && !files.app.includes("resources.forEach((resource) => {\n    if (resource.id === excludedId) return;") && !files.app.includes("[\"active\", \"focus\"].includes(project.status)")],
  ["drag lane counts reuse board buckets", () => files.app.includes("const boxBuckets = boxVisibilityBuckets(state.boxes, itemId)") && files.app.includes("const resourceBuckets = resourceDisplayBuckets(state.resources, itemId)") && !files.app.includes("state.resources.filter((resource) => resource.pinned && resource.id !== itemId") && !files.app.includes("state.boxes.filter((box) => box.visibility === \"pinned\" && box.id !== itemId")],
  ["resource note drag reuses the active note reference", () => files.app.includes("ui.resourceDrag = {\n    id: resourceId,\n    note,") && files.app.includes("const note = drag.note;") && !files.app.includes("const note = ui.resourceNotes.find((entry) => entry.id === drag.id);")],
  ["resource note state reuses lookup and dock helpers", () => files.app.includes("function resourceNoteById(resourceId)") && files.app.includes("for (const note of ui.resourceNotes)") && files.app.includes("function undockResourceNoteInSlot(resourceId, mode)") && files.app.includes("function resourceSplitNotes()") && files.app.includes("function syncResourceNoteElements()") && !files.app.includes("ui.resourceNotes.find((entry) => entry.id === resourceId)") && !files.app.includes("ui.resourceNotes.find((note) => note.id === resourceId)") && !files.app.includes("ui.resourceNotes.forEach(syncResourceNoteElement)")],
  ["resource note rerenders preserve independent scroll positions", () => files.app.includes("function captureResourceNoteViewState()") && files.app.includes("function restoreResourceNoteViewState()") && files.app.includes("note.scrollTop = scroll.scrollTop;") && files.app.includes("restoreResourceNoteScrollPosition(scroll, note);")],
  ["point-based drag targets avoid map-find allocation", () => files.app.includes("function closestElementFromPoint(clientX, clientY, selector)") && files.app.includes("for (const entry of document.elementsFromPoint(clientX, clientY))") && files.app.includes('closestElementFromPoint(clientX, clientY, "[data-drop-date], [data-today-task-action]")') && files.app.includes('closestElementFromPoint(clientX, clientY, "[data-delete-drop]")') && !files.app.includes(".elementsFromPoint(clientX, clientY)\n    .map")],
  ["nav drag track target avoids Array.from filter allocation", () => files.app.includes('for (const button of track.querySelectorAll("[data-nav-key]"))') && files.app.includes("let lastButton = null;") && files.app.includes('if (button.dataset.navKey === ui.navDragKey) continue;') && !files.app.includes('Array.from(track.querySelectorAll("[data-nav-key]")).filter')],
  ["inbox captures classify statuses once", () => files.app.includes("function captureStatusBuckets(captures = state.captures)") && files.app.includes("const captures = controlledItems(\"captures\", state.captures, \"inbox\")") && files.app.includes("const captureBuckets = captureStatusBuckets(captures)") && !files.app.includes("state.captures.filter((capture) => capture.status")],
  ["inbox captures classify with a direct loop", () => files.app.includes("function captureStatusBuckets(captures = state.captures)") && files.app.includes("for (const capture of captures)") && !files.app.includes("captures.forEach((capture)")],
  ["card list renderers avoid map join allocations", () => files.app.includes("function renderTaskCards(tasks, options = {}, emptyText = \"항목이 없습니다.\")") && files.app.includes("function renderResourceCards(resources, emptyText = \"자료가 없습니다.\")") && files.app.includes("function renderCaptureCards(captures, emptyText = \"항목이 없습니다.\")") && files.app.includes("function renderHabitCards(habits, today, emptyText = \"루틴이 없습니다.\")") && files.app.includes("function renderProjectItems(projects, statsByProjectId = null, emptyText = \"프로젝트가 없습니다.\")") && files.app.includes("function renderBoxCards(boxes, statsByBoxId = null, emptyText = \"박스가 없습니다.\")") && files.app.includes("function renderProjectResources(resources)") && files.app.includes("function renderProjectTaskLines(tasks)") && !files.app.includes("todayTasks.map((task) => renderTaskCard") && !files.app.includes("completed.map(renderTaskCard)") && !files.app.includes("captureBuckets.inbox.map(renderCaptureCard)") && !files.app.includes("tasks.map((task) => renderTaskCard") && !files.app.includes("projects.map((project) => renderProjectItem") && !files.app.includes("boxes.map((box) => renderBoxCard") && !files.app.includes("resources.map(renderResourceCard)") && !files.app.includes("resources.map(renderProjectResource)") && !files.app.includes("tasks.map(renderProjectTaskLine)")],
  ["calendar and journal renderers avoid map join chains", () => files.app.includes("function renderProjectCalendarDays(days, options = {})") && files.app.includes("function renderProjectCalendarSpanLayer(rowLayout, limit)") && files.app.includes("function renderJournalCards(journals = state.journals)") && files.app.includes("function renderCombinedCalendarDays(days, eventsByDate, currentMonth, today, calendarThemes)") && files.app.includes("function renderCalendarEvents(events, { compact = false, limit = Infinity, emptyHtml = \"\", calendarThemes } = {})") && files.app.includes("for (let index = 0; index < days.length; index += 1)") && files.app.includes("for (const journal of journals)") && files.app.includes("for (let index = 0; index < count; index += 1)") && !files.app.includes("days.map((day) => renderProjectCalendarDay") && !files.app.includes("rowLayout.segments.map(") && !files.app.includes(".map(renderJournalCard)") && !files.app.includes("dayEvents.map(renderCalendarEvent)") && !files.app.includes("visibleEvents.map((event) => renderCalendarEvent")],
  ["remaining collection renderers avoid map join chains", () => files.app.includes("function renderGoalCards(goals, statsByGoalId)") && files.app.includes("function renderGoogleCalendarToggles(calendars, eventCounts, calendarThemes)") && files.app.includes("function renderHabitDayButtons(habit, days, today)") && files.app.includes("function renderHabitCalendarDays(habit, days, currentMonth, today)") && files.app.includes("function renderResourceNotes(options = {})") && files.app.includes("function renderBlocks(blocksList, ownerType, ownerId)") && files.app.includes("function renderDeleteDragActions(actions, targetAction)") && !files.app.includes("state.goals.map((goal) => renderGoalCard") && !files.app.includes("googleCalendars.map((calendar) => renderGoogleCalendarToggle") && !files.app.includes("days.map((date) => renderHabitDayButton") && !files.app.includes("days.map((day) => {") && !files.app.includes("ui.resourceNotes\n    .map") && !files.app.includes("safeBlocks.map((block) => renderBlock") && !files.app.includes("actions.map((action) => `")],
  ["task card reorder captures rects without map allocation", () => files.app.includes("function captureCardRects()") && files.app.includes("const rects = new Map();") && files.app.includes('els.viewRoot.querySelectorAll(".card[data-task-id]").forEach((card) =>') && !files.app.includes('Array.from(els.viewRoot.querySelectorAll(".card[data-task-id]")).map')],
  ["task card reorder animation avoids Array.from allocation", () => files.app.includes("function animateCardReorder(previousRects)") && files.app.includes('const cards = els.viewRoot.querySelectorAll(".card[data-task-id]");') && files.app.includes("for (const card of cards)") && !files.app.includes('Array.from(els.viewRoot.querySelectorAll(".card[data-task-id]"))')],
  ["block editor drag target avoids Array.from filter-find allocation", () => files.app.includes("const dragIds = new Set(ui.blockDrag?.dragIds || []);") && files.app.includes("let firstBlock = null;") && files.app.includes('editor.querySelectorAll(".block").forEach((block) =>') && !files.app.includes('Array.from(editor.querySelectorAll(".block")).filter') && !files.app.includes("const blocksList =")],
  ["block movement classifies moved and remaining blocks in one pass", () => files.app.includes("const remaining = [];") && files.app.includes("const movedIds = [];") && files.app.includes("item.blocks.forEach((block) =>") && files.app.includes("ui.blockSelection = movedIds.length > 1") && !files.app.includes("const moving = item.blocks.filter") && !files.app.includes("item.blocks = item.blocks.filter((block) => !moveSet.has(block.id));")],
  ["selected block deletion compacts blocks in one pass", () => files.app.includes("function deleteSelectedBlocks()") && files.app.includes("const selectedIds = new Set(selection.ids);") && files.app.includes("let writeIndex = 0;") && files.app.includes("item.blocks[writeIndex] = block;") && files.app.includes("item.blocks.length = writeIndex;") && !files.app.includes("item.blocks = item.blocks.filter((block) => !selection.ids.includes(block.id));")],
  ["ordered selected blocks avoid map-filter allocation", () => files.app.includes("function orderedSelectedBlockIds(editor)") && files.app.includes("const selected = new Set(ui.blockSelection.ids);") && files.app.includes("const ids = [];") && !files.app.includes('Array.from(editor.querySelectorAll(".block"))\n    .map')],
  ["today task props root uses direct data selector", () => files.app.includes("function findTodayTaskPropsRoot(taskId)") && files.app.includes('return app.querySelector(`[data-task-props="${cssEscape(taskId)}"]`);') && !files.app.includes('Array.from(app.querySelectorAll("[data-task-props]")).find')],
  ["today task property choice commit avoids Array.from find", () => files.app.includes("function animateTodayTaskPropertyChoiceCommit") && files.app.includes('const choices = group.querySelectorAll(".task-property-choice");') && files.app.includes("let selected = choice;") && files.app.includes("for (const entry of choices)") && !files.app.includes('Array.from(group.querySelectorAll(".task-property-choice"))') && !files.app.includes("choices.find((entry)")],
  ["today task property panels avoid per-render config allocation", () => files.app.includes("const TASK_PROPERTY_SUMMARY_FIELDS = [") && files.app.includes("const TASK_PROPERTY_LABELS = {") && files.app.includes("const TASK_PROPERTY_HINTS = {") && files.app.includes("const TASK_PROPERTY_COLLECTIONS = {") && files.app.includes("const TASK_DATE_CHOICE_DEFS = [") && files.app.includes("function taskPropertySummaryValue(task, field)") && files.app.includes("function renderTaskDatePropertyChoices(task, field)") && files.app.includes("for (const [field, label] of TASK_PROPERTY_SUMMARY_FIELDS)") && files.app.includes("for (const item of items)") && files.app.includes("for (const [offset, label] of TASK_DATE_CHOICE_DEFS)") && !files.app.includes("function taskDateChoices()") && !files.app.includes("const labels = {\n    title: \"제목\"") && !files.app.includes("const collections = {\n    boxId:") && !files.app.includes("taskDateChoices().map")],
  ["markdown shortcuts are static and scanned without per-input allocation", () => files.app.includes("const MARKDOWN_SHORTCUTS = [") && files.app.includes("for (const [pattern, type, text] of MARKDOWN_SHORTCUTS)") && !files.app.includes("function applyMarkdownShortcut(blockContent, block, rawText) {\n  const shortcuts = [") && !files.app.includes("shortcuts.find(([pattern]) => pattern.test(rawText))")],
  ["soft line breaks stay in-block while structured paste handles multiline and single-line Markdown", () => files.app.includes("function shouldPastePlainTextAsBlocks(event, text)") && files.app.includes("if (/[\\r\\n]/.test(raw)) return true;") && files.app.includes("parseMarkdownInlineText(raw).marks.length") && files.app.includes("function pasteEventBlockContent(event)") && files.app.includes('event.inputType === "insertLineBreak"') && files.app.includes("function insertSoftLineBreak") && files.app.includes("function handlePendingSoftLineBreakBeforeInput") && files.app.includes("function shiftInlineMarksForTextInsertion") && files.app.includes("pendingSoftLineBreakTarget") && !files.app.includes("function splitBlockFromNativeLineBreak") && !files.app.includes("const inserted = parts.map") && !files.app.includes("parts.shift()")],
  ["continued block type lookup is shared instead of per-insert array", () => files.app.includes('const CONTINUED_BLOCK_TYPES = new Set(["bullet", "numbered", "todo"]);') && files.app.includes("CONTINUED_BLOCK_TYPES.has(current.type)") && !files.app.includes('const continuedTypes = ["bullet", "numbered", "todo"];')],
  ["editor caret rect helpers avoid Array.from range allocations", () => files.app.includes("function firstVisibleClientRect(rects)") && files.app.includes("function visibleClientRects(rects)") && files.app.includes("const rect = firstVisibleClientRect(range.getClientRects())") && files.app.includes("return visibleClientRects(range.getClientRects());") && !files.app.includes("Array.from(range.getClientRects()).find") && !files.app.includes("Array.from(range.getClientRects()).filter")],
  ["capture flow animations avoid Array.from find-filter chains", () => files.app.includes('const options = row.querySelectorAll(".capture-flow-option");') && files.app.includes('const flowOptions = row.querySelectorAll(".capture-flow-option");') && files.app.includes("orderedOptions.push({ option, rect, distance:") && files.app.includes("const revealDuration = 360 + orderedOptions.length * 28;") && files.app.includes('flow?.classList.contains("is-flow-collapsing")') && files.app.includes('flow?.querySelector(".is-selecting-choice")') && !files.app.includes('Array.from(row.querySelectorAll(".capture-flow-option")).find') && !files.app.includes('Array.from(row.querySelectorAll(".capture-flow-option")).filter') && !files.app.includes("const hiddenOptions =")],
  ["capture flow collapse classifies rows in one pass", () => files.app.includes("const collapsing = [];") && files.app.includes("let targetRow = null;") && files.app.includes('flow.querySelectorAll(":scope > .capture-flow-row, :scope > .capture-flow-save").forEach((row) =>') && !files.app.includes("const keepRows = rows.filter") && !files.app.includes("const collapsing = rows.filter")],
  ["capture flow options avoid spread-map allocation", () => files.app.includes("const CAPTURE_CONVERT_TYPES = [") && files.app.includes("const RESOURCE_TYPE_CAPTURE_OPTIONS = [") && files.app.includes("function renderTaskCaptureStepOptions(captureId, step, selectedValue)") && files.app.includes("function boxCaptureOptions()") && files.app.includes("function goalCaptureOptions(goals, type)") && files.app.includes("function projectCaptureOptions(projects, type)") && files.app.includes("function resourceCaptureOptions(resources)") && files.app.includes("for (const option of step.options)") && files.app.includes("for (const box of state.boxes)") && files.app.includes("for (const goal of goals)") && files.app.includes("for (const project of projects)") && files.app.includes("for (const resource of resources)") && files.app.includes("for (const option of step.options)") && !files.app.includes("visibleSteps.map") && !files.app.includes("step.options.map") && !files.app.includes("...state.boxes.map") && !files.app.includes("...goals.map") && !files.app.includes("...projects.map") && !files.app.includes("...resources.map") && !files.app.includes("step.options.find") && !files.app.includes("return steps\n    .map")],
  ["project flow metadata avoids array filter join", () => files.app.includes("function projectFlowMeta(project)") && files.app.includes("if (goalName && status) return `${goalName} · ${status}`;") && files.app.includes("return goalName || status;") && !files.app.includes("[goalName, status].filter(Boolean).join")],
  ["capture relation choices reuse relation indexes", () => files.app.includes("let relationIndexCache = null") && files.app.includes("function relationIndex()") && files.app.includes("function captureRelationCandidates") && files.app.includes("const { goals, projects, resources } = captureRelationCandidates") && files.app.includes("resourcesByProjectId,") && !files.app.includes("projectBelongsToBox") && !files.app.includes("state.resources.filter((resource) => resource.projectId === projectId")],
  ["relation index covers stats relationship maps", () => files.app.includes("const tasksByProjectId = new Map();") && files.app.includes("const resourcesByProjectId = new Map();") && files.app.includes("const habitsByProjectId = new Map();") && files.app.includes("projectsByGoalId") && files.app.includes("cached?.tasks === state.tasks") && files.app.includes("cached?.habits === state.habits")],
  ["relation index builds relationship maps in single collection passes", () => files.app.includes("for (const goal of state.goals)") && files.app.includes("for (const project of state.projects)") && files.app.includes("for (const task of state.tasks)") && files.app.includes("for (const resource of state.resources)") && files.app.includes("for (const habit of state.habits)") && files.app.includes("const inheritedBoxId = goalsById.get(project.goalId)?.boxId;") && !files.app.includes("function groupByProjectId") && !files.app.includes("function groupByField") && !files.app.includes("groupByField(state.") && !files.app.includes("groupByProjectId(state.") && !files.app.includes("new Set([project.boxId")],
  ["project board reuses indexed project stats", () => files.app.includes("const statsByProjectId = projectStatsIndex()") && files.app.includes("const statsByProjectId = new Map();") && files.app.includes("statsByProjectId.set(") && files.app.includes("function projectStatsRelations(project)") && files.app.includes("renderProjectItem(project, statsByProjectId)") && !files.app.includes("function projectStats(project, tasks = state.tasks.filter") && !files.app.includes("return new Map(\n    state.projects.map")],
  ["goal and box boards reuse indexed entity stats", () => files.app.includes("const statsByGoalId = goalStatsIndex()") && files.app.includes("const statsByBoxId = boxStatsIndex()") && files.app.includes("function goalStatsRelations(goal)") && files.app.includes("function boxStatsRelations(box)") && files.app.includes("function mergeUniqueIndexedItems(baseItems = [], ...indexedGroups)") && files.app.includes("function appendUniqueItems(merged, seen, items = [])") && files.app.includes("renderGoalCard(goal, statsByGoalId)") && files.app.includes("renderBoxCard(box, statsByBoxId)") && !files.app.includes("const projectsByGoalId = groupByField(state.projects, \"goalId\");\n  const tasksByGoalId") && !files.app.includes("const goalsByBoxId = groupByField(state.goals, \"boxId\");\n  const projectsByBoxId")],
  ["entity stat indexes avoid map-spread-flat intermediates", () => files.app.includes("for (const project of state.projects)") && files.app.includes("for (const goal of state.goals)") && files.app.includes("for (const box of state.boxes)") && files.app.includes("appendUniqueItems(merged, seen, index.get(item.id) || [])") && !files.app.includes("groups.flat()") && !files.app.includes("...projects.map((project) => index.tasksByProjectId.get(project.id) || [])") && !files.app.includes("...goals.map((goal) => index.tasksByGoalId.get(goal.id) || [])") && !files.app.includes("return new Map(\n    state.goals.map") && !files.app.includes("return new Map(\n    state.boxes.map")],
  ["entity stats count relation arrays in one pass", () => files.app.includes("function projectDetailTaskGroups(tasks = [])") && files.app.includes("function taskStatusCounts(tasks, today = \"\")") && files.app.includes("for (const task of tasks)") && files.app.includes("function projectStatusCounts(projects)") && files.app.includes("for (const project of projects)") && files.app.includes("function resourceStatusCounts(resources)") && files.app.includes("for (const resource of resources)") && files.app.includes("function habitStatusCounts(habits)") && files.app.includes("for (const habit of habits)") && !files.app.includes("tasks.filter((task) => task.status === \"done\").length") && !files.app.includes("tasks.filter(isOverdue).length") && !files.app.includes("projects.filter((project) => project.status === \"completed\").length") && !files.app.includes("resources.filter((resource) => resource.importance === \"important\").length") && !files.app.includes("habits.filter((habit) => habit.status === \"active\").length")],
  ["project detail task grouping uses a direct loop", () => files.app.includes("function projectDetailTaskGroups(tasks = [])") && files.app.includes("for (const task of tasks)") && !/function projectDetailTaskGroups\(tasks = \[\]\) \{[\s\S]*?tasks\.forEach[\s\S]*?function renderProjectRelation/.test(files.app)],
  ["storage tracks normalization changes without full stringify comparison", () => files.storage.includes("let changed = !validRoot") && !files.storage.includes("JSON.stringify(normalized.state) !== JSON.stringify") && !files.storage.includes("JSON.stringify(nextState) !== JSON.stringify")],
  ["storage normalization avoids JSON clone before JSONB writes", () => files.storage.includes("const nextState = validRoot ? state : {};") && !files.storage.includes("JSON.parse(JSON.stringify(state))")],
  ["storage collection normalization lazily clones only dirty arrays", () => files.storage.includes("let normalizedItems = null;") && files.storage.includes("const items = nextState[key];") && files.storage.includes("normalizedItems = items.slice(0, index);") && files.storage.includes("if (normalizedItems) normalizedItems.push(item);") && files.storage.includes("if (normalizedItems) nextState[key] = normalizedItems;") && !files.storage.includes("const normalizedItems = [];")],
  ["storage calendar source normalization reuses valid objects", () => files.storage.includes("const CALENDAR_SOURCE_KEY_SET = new Set(CALENDAR_SOURCE_KEYS);") && files.storage.includes("function calendarSourcesValid(sources)") && files.storage.includes("if (calendarSourcesValid(sources)) return sources;") && files.storage.includes("for (const key in sources)") && files.storage.includes("return count === CALENDAR_SOURCE_KEYS.length;")],
  ["storage shallow object comparison avoids key arrays", () => files.storage.includes("function shallowObjectsEqual(left, right)") && files.storage.includes("let leftCount = 0;") && files.storage.includes("let rightCount = 0;") && files.storage.includes("return leftCount === rightCount;") && !files.storage.includes("const leftKeys = Object.keys(left);") && !files.storage.includes("const rightKeys = Object.keys(right);")],
  ["state normalization hot paths avoid forEach/every callbacks", () => files.app.includes("function objectArrayOrFallback(value, fallback)") && files.app.includes("function objectArrayWithoutLegacyKind(value, fallback)") && !files.app.includes("source.forEach((item, index) =>") && !files.app.includes("order.forEach((key)") && !files.app.includes("CALENDAR_SOURCE_KEYS.forEach") && !files.app.includes("googleCalendars.forEach") && !files.app.includes("keys.every(") && !files.app.includes("CALENDAR_SOURCE_KEYS.every(") && !files.storage.includes("order.forEach((key)") && !files.storage.includes("DEFAULT_NAV_ORDER.forEach") && !files.storage.includes("CALENDAR_SOURCE_KEYS.forEach") && !files.storage.includes("STRING_SETTING_KEYS.forEach") && !files.storage.includes("COLLECTION_KEYS.forEach") && !files.storage.includes("left.every(") && !files.storage.includes("leftKeys.every(")],
  ["storage boolean map normalization avoids entries-filter chains", () => files.storage.includes("function normalizeBooleanMap(map)") && files.storage.includes("const normalized = {};") && files.storage.includes("for (const key in map)") && files.storage.includes("Object.prototype.hasOwnProperty.call(map, key)") && !files.storage.includes("Object.fromEntries(Object.entries(map).filter")],
  ["state write API returns relationally reconstructed state", () => files.storage.includes("state: relationalState") && files.storage.includes("await readRelationalAppState(client, normalized.state)") && files.server.includes("...saved") && files.app.includes("state = normalizeState(payload.state)")],
  ["Google token store is PostgreSQL only", () => files.storage.includes('writePrivateData("google_token"') && files.server.includes('tokenStore: "postgresql"') && !files.server.includes('"file"')],
  ["localStorage cannot act as workspace state authority", () => !files.app.includes("localStorage.setItem") && !files.app.includes("localStorage.getItem(LEGACY_STORAGE_KEY)") && files.app.includes("clearLegacyLocalState()")],
  ["browser storage writes are not used for runtime data", () => !files.app.includes("sessionStorage.") && !files.app.includes("localStorage.setItem")],
  ["legacy localStorage cleanup cannot fail PostgreSQL saves", () => /function clearLegacyLocalState\(\) \{\s*try \{\s*localStorage\.removeItem\(LEGACY_STORAGE_KEY\);\s*\} catch \{\}\s*\}/s.test(files.app)],
  ["page exit state save uses beacon or keepalive", () => files.app.includes("navigator.sendBeacon") && files.app.includes("handlePageHideStateSave") && files.app.includes("keepalive: Boolean(options.keepalive)")],
  ["remote state saves serialize one revision-preconditioned snapshot", () => files.app.includes("function stateRequestBody(baseRevision = currentWorkspaceRevision())") && files.app.includes("return JSON.stringify({ state, baseRevision });") && files.app.includes("const outgoingUpdatedAt = state.updatedAt") && files.app.includes("const baseRevision = currentWorkspaceRevision()") && files.app.includes("const body = stateRequestBody(baseRevision)") && files.app.includes('headers: { "If-Match": `"state-${baseRevision}"` }') && files.app.includes("body,") && !files.app.includes("function stateSnapshot()") && !files.app.includes("JSON.parse(JSON.stringify(state))")],
  ["database schema render avoids nested map chains", () => files.app.includes("function renderDatabaseModelGrid(nodes = DB_SCHEMA)") && files.app.includes("function renderDatabaseModelFields(fields)") && files.app.includes("function renderDatabaseModelRelations(relations)") && files.app.includes("for (const node of nodes)") && files.app.includes("for (const field of fields)") && files.app.includes("for (const relation of relations)") && !files.app.includes("DB_SCHEMA.map") && !files.app.includes("node.fields.map") && !files.app.includes("node.relations.map")],
  ["database total block count avoids spread-reduce allocation", () => files.app.includes("function totalBlocks()") && files.app.includes("function blockCountForItems(items)") && files.app.includes("total += blockCountForItems(state.boxes);") && !files.app.includes("[...state.boxes, ...state.goals") && !/function totalBlocks\(\) \{[\s\S]*?\.reduce\(/.test(files.app)],
  ["database settings count avoids Object.keys allocation", () => files.app.includes("function settingsCount()") && files.app.includes("for (const key in state.settings)") && files.app.includes("return settingsCount();") && !files.app.includes("Object.keys(state.settings).length")],
  ["form select options render with direct loops", () => files.app.includes("function renderSelectOptions(options, value)") && files.app.includes("function renderRelationOptions(items, value, nameField)") && files.app.includes("for (const key in options)") && files.app.includes("Object.prototype.hasOwnProperty.call(options, key)") && files.app.includes("for (const item of items)") && !files.app.includes("Object.entries(options)") && !files.app.includes("items\n          .map((item) => `<option")],
  ["Google status refresh saves only when connection metadata changes", () => files.app.includes("const connectedAt = payload.connectedAt || state.settings.googleConnectedAt || new Date().toISOString()") && files.app.includes("if (state.settings.googleConnectedAt !== connectedAt)")],
  ["Google calendar server response avoids callback and map-flat allocation", () => files.server.includes("const eventRequests = [];") && files.server.includes("for (const calendar of calendars)") && files.server.includes("for (let index = 0; index < eventGroups.length; index += 1)") && files.server.includes("for (const event of calendarEvents)") && files.server.includes("events.push({ calendar, event });") && !files.server.includes("calendars.forEach((calendar)") && !files.server.includes("eventGroups.forEach((calendarEvents") && !files.server.includes("eventGroups.flat()") && !files.server.includes("return events.map((event)")],
  ["state API accepts beacon POST writes", () => files.server.includes('request.method === "PUT" || request.method === "POST"') && files.checkPostgres.includes('method: "POST"')],
  ["state API returns INVALID_JSON/400 for malformed JSON", () => files.server.includes('apiError(400, "INVALID_JSON", "Invalid JSON body.")') && files.checkPostgres.includes('invalidJsonResult.response.status === 400 && invalidJsonResult.payload.code === "INVALID_JSON"') && files.checkPostgres.includes("invalid JSON state write should return INVALID_JSON/400")],
  ["static responses cache only content-hashed assets", () => files.server.includes("staticCacheControl") && files.server.includes('"X-Content-Type-Options": "nosniff"') && files.server.includes("public, max-age=31536000, immutable") && files.checkPostgres.includes("query-versioned source assets must not be cached")],
  ["static responses support compression and validators", () => files.server.includes("brotliCompressAsync") && files.server.includes("gzipAsync") && files.server.includes('request.headers["if-none-match"]') && files.server.includes('"Content-Encoding"') && files.server.includes('Vary: "Accept-Encoding"')],
  ["static HEAD requests are supported", () => files.server.includes('request.method === "HEAD"') && files.checkPostgres.includes('method: "HEAD"')],
  ["server env and cookie parsers avoid filter-map chains", () => files.server.includes("for (const rawLine of raw.split(/\\r?\\n/))") && files.server.includes("const cookies = Object.create(null);") && files.server.includes('for (const rawPart of String(request.headers.cookie || "").split(";"))') && !files.server.includes("Object.fromEntries(") && !files.server.includes(".filter(Boolean)")],
  ["env example documents required PostgreSQL persistence", () => files.envExample.includes("DATABASE_URL=") && files.envExample.includes("Required for app state and private integration data") && !files.envExample.includes("REQUIRE_DATABASE")],
  ["README documents PostgreSQL verification", () => files.readme.includes("npm run check:postgres") && files.readme.includes("app_private_data") && files.readme.includes("task_resources")],
  ["package check runs source audit", () => files.packageJson.scripts?.check?.includes("scripts/audit-source.mjs")],
  ["package check has PostgreSQL smoke script", () => files.packageJson.scripts?.["check:postgres"]?.includes("scripts/check-postgres-state.mjs")],
  ["package check has isolated migration backup script", () => files.packageJson.scripts?.["check:backups"]?.includes("scripts/check-state-migration-backups.mjs") && files.packageJson.scripts?.check?.includes("scripts/manage-state-backups.mjs")],
  ["package has a minified content-hashed Railway production build", () => files.packageJson.scripts?.build === "node scripts/build.mjs" && files.build.includes('minify: true') && files.build.includes("contentHash") && !files.build.includes('resolve(dist, "server/index.js")') && !files.build.includes('resolve(clientDir, "_headers")') && files.railway.build?.buildCommand === "npm run check && npm run check:build"],
  ["Sites deployment artifacts are removed", () => !existsSync("worker/index.js") && !existsSync(".openai/hosting.json") && !existsSync("scripts/check-worker.mjs") && !existsSync("scripts/check-api-proxy-auth.mjs") && !existsSync("scripts/configure-api-proxy-auth.mjs")],
  ["PostgreSQL smoke script cleans test rows", () => files.checkPostgres.includes("cleanupCheckRows") && files.checkPostgres.includes("DELETE FROM app_state") && files.checkPostgres.includes("DELETE FROM app_private_data")],
  ["PostgreSQL smoke script verifies all app collections round-trip", () => files.checkPostgres.includes("const COLLECTION_KEYS = [") && files.checkPostgres.includes('"captures"') && files.checkPostgres.includes('"habitInstances"') && files.checkPostgres.includes('"googleEvents"') && files.checkPostgres.includes('"links"') && files.checkPostgres.includes("for (const key of COLLECTION_KEYS)") && files.checkPostgres.includes("jsonb_array_length(state->'captures') AS capture_count") && files.checkPostgres.includes("jsonb_array_length(state->'links') AS link_count")],
  ["PostgreSQL smoke script verifies relational tables and links", () => files.checkPostgres.includes("relationalCounts") && files.checkPostgres.includes("FROM task_resources") && files.checkPostgres.includes("relational tasks did not preserve box/goal/project references") && files.checkPostgres.includes("task-resource relation was not stored as a separate relationship")],
  ["PostgreSQL smoke script verifies relational tables are source of truth", () => files.checkPostgres.includes("Relational table task title") && files.checkPostgres.includes("state read did not use the relational tasks table as source of truth") && files.checkPostgres.includes("stale JSONB app_state overrode the relational task table")],
  ["PostgreSQL smoke script verifies strict 422 rejection without mutation", () => files.checkPostgres.includes("async function assertInvalidWriteDoesNotMutate") && files.checkPostgres.includes('result.response.status === 422 && result.payload.code === "INVALID_STATE"') && files.checkPostgres.includes("duplicate ID") && files.checkPostgres.includes("broken relation") && files.checkPostgres.includes("unsafe URL") && files.checkPostgres.includes("invalid Resource block") && files.checkPostgres.includes("rejection changed the stored revision") && files.checkPostgres.includes("rejection mutated the stored state") && files.checkPostgres.includes("rejection mutated readable state")],
  ["PostgreSQL smoke script verifies read healing", () => files.checkPostgres.includes("pollutedState") && files.checkPostgres.includes("state read did not heal polluted PostgreSQL collections/settings")],
  ["PostgreSQL smoke script verifies legacy token migration", () => files.checkPostgres.includes("legacyTokenFile") && files.checkPostgres.includes("legacy Google token file was not migrated into PostgreSQL") && files.checkPostgres.includes("legacy Google token file was not removed after migration")],
  ["service worker skips API caching", () => files.serviceWorker.includes('url.pathname.startsWith("/api/")')],
  ["service worker cache-first is limited to content-hashed assets", () => files.serviceWorker.includes("function cacheFirst(request)") && files.serviceWorker.includes("immutableAsset ? cacheFirst") && files.serviceWorker.includes('url.pathname.startsWith("/_sygma/assets/")') && !files.serviceWorker.includes('url.searchParams.has("v")') && !files.serviceWorker.includes('url.pathname.startsWith("/icons/")')],
  ["state revision events drive immediate browser refresh", () => files.server.includes('pathname === "/api/state/events"') && files.server.includes("handleStateEvents(request, response)") && files.server.includes("broadcastStateEvent(saved.revision") && files.app.includes('new EventSource("/api/state/events")') && files.app.includes("refreshRemoteStateIfNewer()")],
  ["offline startup retries without relying on browser online events", () => files.app.includes("if (!databaseBackendStatus.connected || navigator.onLine === false)") && files.app.includes("handleResourceConnectionRestored();") && files.app.includes("scheduleRemoteStateRefresh();")],
  ["browser API requests bypass HTTP caches", () => /async function apiJson[\s\S]*?fetch\(path, \{\s*cache: "no-store"/.test(files.app)],
  ["safe service-worker updates apply automatically", () => files.app.includes("if (!hasUnsavedResourceWork())") && files.app.includes("applyWaitingServiceWorkerUpdate();") && files.app.includes("checkForServiceWorkerUpdate()")],
  ["index and service worker cache the same app/style URLs", () => cachedAssetUrlsMatchIndex()],
  ["pointer listeners avoid duplicate mouse compatibility events", () => files.app.includes('const pointerEventsSupported = "PointerEvent" in window;') && files.app.includes("document.addEventListener(pointerMoveEvent") && !files.app.includes('app.addEventListener("mousedown", handlePointerDown)')],
  ["Today task drag exposes and commits an accessible delete drop target", () => files.app.includes('data-today-task-action="delete"') && files.app.includes('aria-label="할 일 삭제"') && files.app.includes('"[data-drop-date], [data-today-task-action]"') && files.app.includes('commitDragAction("tasks", task.id, "delete")') && files.styles.includes(".today-delete-drop") && files.styles.includes(".today-delete-drop.is-over")],
  ["block icon hover work is animation-frame throttled", () => files.app.includes("function scheduleBlockIconHoverPointerMove(event)") && files.app.includes("blockIconHoverFrame = window.requestAnimationFrame")],
  ["resource editor commands avoid full page rerenders", () => {
    const start = files.app.indexOf("function toggleAllTogglesInEditor");
    const end = files.app.indexOf("function inlineRangeFullyMarked", start);
    const editorCommands = start >= 0 && end > start ? files.app.slice(start, end) : "";
    return editorCommands.includes("renderEditorMutation(") && !editorCommands.includes("renderDetail({ soft: true });") && !editorCommands.includes("renderView({ soft: true });");
  }],
  ["no apparently unused named function or arrow declarations", () => noApparentlyUnusedFunctions()],
  ["no unreferenced CSS class selectors", () => noUnreferencedCssClassSelectors()],
];

const failures = checks.filter(([, check]) => !check()).map(([label]) => label);
if (failures.length) {
  console.error(`Source audit failed:\n${failures.map((label) => `- ${label}`).join("\n")}`);
  process.exit(1);
}

console.log("Source audit passed.");

function read(path) {
  return readFileSync(path, "utf8");
}

function sourceSection(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start + startMarker.length);
  return start >= 0 && end > start ? source.slice(start, end) : "";
}

function cachedAssetUrlsMatchIndex() {
  const indexAssets = [
    matchRequired(files.index, /href="((?:\.\/|\/)styles\.css\?v=[^"]+)"/, "index stylesheet"),
    matchRequired(files.index, /src="((?:\.\/|\/)app\.js\?v=[^"]+)"/, "index script"),
  ];
  return indexAssets.every((asset) => files.serviceWorker.includes(`"${asset}"`));
}

function matchRequired(source, pattern, label) {
  const match = source.match(pattern);
  if (!match) throw new Error(`${label} not found`);
  return match[1];
}

function noApparentlyUnusedFunctions() {
  const source = [files.app, files.server, files.storage, files.checkPostgres].join("\n");
  const code = stripQuotedStringsAndComments(source);
  const names = new Set([
    ...code.matchAll(/\bfunction\s+([A-Za-z_$][\w$]*)\s*\(/g),
    ...code.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>/g),
  ].map((match) => match[1]));
  const unused = [];
  for (const name of names) {
    const count = (source.match(new RegExp(`\\b${name}\\b`, "g")) || []).length;
    if (count <= 1) unused.push(name);
  }
  if (!unused.length) return true;
  console.error(`Apparently unused functions: ${unused.join(", ")}`);
  return false;
}

function stripQuotedStringsAndComments(source) {
  let output = "";
  let quote = "";
  let inLineComment = false;
  let inBlockComment = false;
  let inTemplate = false;
  let escaped = false;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    const next = source[index + 1];

    if (inLineComment) {
      output += char === "\n" ? "\n" : " ";
      if (char === "\n") inLineComment = false;
      continue;
    }

    if (inBlockComment) {
      if (char === "*" && next === "/") {
        output += "  ";
        index += 1;
        inBlockComment = false;
      } else {
        output += char === "\n" ? "\n" : " ";
      }
      continue;
    }

    if (quote) {
      output += char === "\n" ? "\n" : " ";
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === quote) {
        quote = "";
      }
      continue;
    }

    if (inTemplate) {
      output += char;
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "`") {
        inTemplate = false;
      }
      continue;
    }

    if (char === "/" && next === "/") {
      output += "  ";
      index += 1;
      inLineComment = true;
      continue;
    }

    if (char === "/" && next === "*") {
      output += "  ";
      index += 1;
      inBlockComment = true;
      continue;
    }

    if (char === "\"" || char === "'") {
      output += " ";
      quote = char;
      escaped = false;
      continue;
    }

    if (char === "`") {
      output += char;
      inTemplate = true;
      escaped = false;
      continue;
    }

    output += char;
  }
  return output;
}

function noUnreferencedCssClassSelectors() {
  const source = `${files.app}\n${files.index}`;
  const classNames = new Set([...files.styles.matchAll(/\.([A-Za-z_-][\w-]*)/g)].map((match) => match[1]));
  for (const className of classNames) {
    if (!source.includes(className)) return false;
  }
  return true;
}
